spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: admin
    password: admin
  jpa:
    generate-ddl: false
    show-sql: true
  liquibase:
    enabled: true
deal:
  rest-client:
    root-uri: 'http://localhost:8080/calculator/'
logging:
  level:
    root: debug