db:
  schema:
    name: 'bank'
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/bank_db
    username: admin
    password: admin
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        default_schema: ${db.schema.name}
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    default-schema: ${db.schema.name}
    liquibase-schema: ${db.schema.name}
deal:
  rest-client:
    root-uri: http://host.docker.internal:8080/calculator/
logging:
  level:
    root: info