db:
  schema:
    name: ${DB_SCHEMA}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        default_schema: ${db.schema.name}
  liquibase:
    enabled: true
    default-schema: ${db.schema.name}
    liquibase-schema: ${db.schema.name}
deal:
  rest-client:
    root-uri: ${ROOT_URI}
logging:
  level:
    root: info