db:
  schema:
    name: 'bank'
spring:
  datasource:
    url: jdbc:tc:postgresql://localhost:5432/test
    username: admin
    password: admin
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        default_schema: ${db.schema.name}
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    default-schema: ${db.schema.name}
    liquibase-schema: ${db.schema.name}
deal:
  rest-client:
    root-uri: 'http://localhost:8090/calculator/'
logging:
  level:
    root: info