spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: false
    show-sql: false
  liquibase:
    enabled: true
logging:
  level:
    root: info